"""added insurance fields

Revision ID: 5c91d002eca9
Revises: b88f9138b3f7
Create Date: 2024-12-07 23:35:19.128512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c91d002eca9'
down_revision = 'b88f9138b3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kyc_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kyc_document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('business_document_url')
        batch_op.drop_column('kyc_document_url')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('otp_verified')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
