"""added account type to be an integer

Revision ID: 95645f864328
Revises: 8c4c1536e8a9
Create Date: 2024-11-18 05:50:34.632845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95645f864328'
down_revision = '8c4c1536e8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.Integer(), nullable=True))

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.Integer(), nullable=True))

    with op.batch_alter_table('insurance_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_companies', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
