"""first migration

Revision ID: 9659f3963564
Revises: 
Create Date: 2024-11-16 16:21:51.214142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9659f3963564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('kyc_document_url', sa.String(length=255), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('distributors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('representative_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('kyb_status', sa.String(length=20), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('kyc_document_url', sa.String(length=255), nullable=True),
    sa.Column('business_document_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('insurance_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('contact_email', sa.String(length=128), nullable=False),
    sa.Column('contact_phone', sa.String(length=64), nullable=False),
    sa.Column('kyb_status', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('product_category', sa.String(length=120), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('receipt_image', sa.String(length=255), nullable=True),
    sa.Column('product_image', sa.String(length=255), nullable=True),
    sa.Column('purchase_status', sa.String(length=20), nullable=True),
    sa.Column('purchase_secret', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('distributor_id', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_secret')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_table('insurance_companies')
    op.drop_table('distributors')
    op.drop_table('agents')
    # ### end Alembic commands ###
