"""added policy

Revision ID: b88f9138b3f7
Revises: d462115f46d2
Create Date: 2024-12-07 22:34:25.502837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b88f9138b3f7'
down_revision = 'd462115f46d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('insurance_company_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['insurance_company_id'], ['insurance_company.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('insurance_companies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_companies',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contact_phone', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('kyb_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('account_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('updated', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('policy')
    # ### end Alembic commands ###
