"""agent to distributor relationship

Revision ID: f7681cf6587a
Revises: a3c543a44260
Create Date: 2024-11-17 00:24:26.254161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7681cf6587a'
down_revision = 'a3c543a44260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distributor_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'distributors', ['distributor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('distributor_id')

    # ### end Alembic commands ###
